services:
  flask-app:
    image: ayocloudpro/gsls_management_system:latest
    container_name: flask-app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql/mydatabase  
    depends_on:
      mysql:
        condition: service_healthy  

  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  nginx:
    image: ayocloudpro/nginx-custom:latest 
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro 
    depends_on:
      - flask-app

volumes:
  mysql_data:
