# Use the official Nginx base image
FROM nginx:latest

# Remove default config
RUN rm -rf /etc/nginx/conf.d/default.conf

# Copy custom Nginx config
COPY mysite.conf /etc/nginx/conf.d/

# Expose Nginx ports
EXPOSE 80 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
