name: Build and Deploy

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/gsls_management_system:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        run: |
          echo "${{secrets.PRIVATE_SSH_KEY}}" > key
          chmod 400 key

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          docker pull ${{ vars.DOCKERHUB_USERNAME }}/gsls_management_system:latest
          docker stop gsls_management_system || true
          docker rm gsls_management_system || true
          docker run -d -p 80:80 --restart=always --name gsls_management_system ${{ vars.DOCKERHUB_USERNAME }}/gsls_management_system:latest
          docker system prune -f
          EOF

      - name: Verify Deployment
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "docker ps"
