name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gsls_management_system:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H gslsportal.com >> ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_SSH_KEY" > ~/.ssh/id_rsa
        chmod 644 .env ~/.ssh/id_rsa
        ssh -i ~/.ssh/id_rsa ay@gslsportal.com '
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/gsls_management_system:latest &&
          (docker stop app || true) &&
          (docker rm app || true) &&
          docker run -d --name app --env-file .env -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/gsls_management_system:latest
        '

    - name: Install Certbot and Obtain SSL Certificate
      run: |
        ssh -i ~/.ssh/id_rsa ay@gslsportal.com '
          sudo apt-get update &&
          sudo apt-get install -y certbot python3-certbot-nginx &&
          sudo certbot --nginx -d gslsportal.com -d www.gslsportal.com --non-interactive --agree-tos --email ayomideolalere374@gmail.com
        '

    - name: Reload Nginx to Apply SSL Certificate
      run: |
        ssh -i ~/.ssh/id_rsa ay@gslsportal.com '
          sudo systemctl reload nginx
        '