name: Build, Push, and Deploy to GCP VM

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub using Token
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH into GCP VM and Deploy Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          script: |
            echo "SSH connection successful!"
            debug: true
            # Pull latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            
            # Stop and remove old container (if exists)
            docker stop my-app || true
            docker rm my-app || true

            # Run new container
            docker run -d --name my-app -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/my-app:latest