name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gsls_management_system:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts  # Ensure the file exists before updating
        ssh-keygen -R gslsportal.comThe failure in the deploy job is due to the `ssh-keyscan || true  # Remove old key (ignore errors)
        ping` command not finding the host `gslsportal.com`. -c 4 gslsportal.com  # Add this line for testing connectivity This issue can occur if the DNS resolution fails or the host is temporarily unreachable.

        ssh-keyscan -H gslsportal.com >> ~/.To handle this, we can add a retry mechanism for thessh/known_hosts

    - name: Reset SSH Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -R gslsportal.com || true
        ssh-keyscan -H gslsportal.com >> ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -i ~/.ssh/id_rsa ay@35.226.78.13 '
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/gsls_management_system:latest &&
          (docker stop app || true) &&
          (docker rm app || true) &&
          docker run -d --name app -e MYSQL_USER=${{ secrets.MYSQL_USER }} -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/gsls_management_system:latest
        '

    - name: Ensure Nginx is Installed and Restart It
      run: |
        ssh -i ~/.ssh/id_rsa ay@35.226.78.13 '
          if ! command -v nginx &> /dev/null
          then
            sudo apt update
            sudo apt install -y nginx
          fi
          sudo systemctl restart nginx
        '

    - name: Install Certbot and Obtain SSL Certificate
      run: |
        ssh -i ~/.ssh/id_rsa ay@35.226.78.13 '
          sudo apt-get update &&
          sudo apt-get install -y certbot python3-certbot-nginx &&
          sudo certbot --nginx -d gslsportal.com -d www.gslsportal.com --non-interactive --agree-tos --email ayomideolalere374@gmail.com
        '

    - name: Reload Nginx to Apply SSL Certificate
      run: |
        ssh -i ~/.ssh/id_rsa ay@35.226.78.13 '
          sudo systemctl reload nginx
        '